"""add text_content url mime fields to sources

Revision ID: 281e0c7fd4bf
Revises: 8e2a1d2eeb8c
Create Date: 2026-02-25 21:27:48.850802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281e0c7fd4bf'
down_revision: Union[str, Sequence[str], None] = '8e2a1d2eeb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('text_content', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('url', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('original_filename', sa.String(), nullable=True))
    op.alter_column('sources', 'storage_uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'storage_uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sources', 'original_filename')
    op.drop_column('sources', 'mime_type')
    op.drop_column('sources', 'url')
    op.drop_column('sources', 'text_content')
    # ### end Alembic commands ###
