"""add storage_uri to sources

Revision ID: 8e2a1d2eeb8c
Revises: 0805af5daffe
Create Date: 2026-02-25 21:13:45.177812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2a1d2eeb8c'
down_revision: Union[str, Sequence[str], None] = '0805af5daffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('storage_uri', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'storage_uri')
    # ### end Alembic commands ###
