"""add column OID <Azure Ad Object ID>  to Users table

Revision ID: d16c605539d9
Revises: 0003
Create Date: 2026-03-06 04:25:07.109521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16c605539d9'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oid', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_users_oid'), 'users', ['oid'], unique=True)
    op.alter_column('workspaces', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_oid'), table_name='users')
    op.drop_column('users', 'oid')
    # ### end Alembic commands ###
