// lib/api.ts
// Real API client for NoteWise.

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

// ---------------------------------------------------------------------------
// Token getter — injected by AuthProvider so this file has no MSAL dependency
// ---------------------------------------------------------------------------

let _getAccessToken: (() => Promise<string | null>) | null = null;

/**
 * Called once by AuthProvider after MSAL is initialised.
 * Provides a way to silently acquire the current access token on every request.
 */
export function setAccessTokenGetter(fn: () => Promise<string | null>) {
  _getAccessToken = fn;
}

async function authHeaders(
  extra?: Record<string, string>,
): Promise<Record<string, string>> {
  const token = _getAccessToken ? await _getAccessToken() : null;
  if (!token) throw new Error("Not authenticated — no access token available");
  return {
    "Content-Type": "application/json",
    Authorization: `Bearer ${token}`,
    ...extra,
  };
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SourceStatus = "pending" | "processing" | "done" | "failed";

export interface Source {
  id: string;
  workspace_id: string;
  source_type: "pdf" | "audio" | "text" | "url";
  title: string;
  /** UI alias used by job-status-panel and source-list */
  name: string;
  /** UI alias used by job-status-panel */
  type: string;
  /** UI alias used by job-status-panel */
  addedAt: string;
  status: SourceStatus;
  storage_uri: string | null;
  text_content: string | null;
  url: string | null;
  mime_type: string | null;
  original_filename: string | null;
  created_at: string;
  latest_summary: string | null;
}

export interface WorkspaceAssets {
  /**
   * TSX component source code generated by Gemini and stored in artifacts.content.
   * Null if not yet generated.
   */
  deepdive: string | null;
}

export interface Job {
  id: string;
  type: "deepdive" | "summary" | "ingest";
  status: "queued" | "running" | "completed" | "failed";
  updatedAt: string;
}

export interface Workspace {
  id: string;
  name: string;
  description: string | null;
  created_at: string;
  sources: Source[];
  summary: string | null;
  latest_summary: string | null;
  assets: WorkspaceAssets;
  jobs: Job[];
}

export interface WorkspaceCard {
  id: string;
  name: string;
  description: string | null;
  source_count: number;
  has_processing: boolean;
  latest_summary: string | null;
  created_at: string;
}

export interface UploadUrlResponse {
  upload_url: string;
  blob_path: string;
}

export interface SourceStatusResponse {
  id: string;
  status: SourceStatus;
  latest_summary: string | null;
}

// ---------------------------------------------------------------------------
// Normalise helpers
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function normaliseSource(s: any): Source {
  return {
    ...s,
    name: s.title ?? s.original_filename ?? "Untitled",
    addedAt: s.created_at,
    type: s.source_type,
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function normaliseWorkspace(raw: any): Workspace {
  return {
    id: raw.id,
    name: raw.name,
    description: raw.description ?? null,
    created_at: raw.created_at,
    sources: (raw.sources ?? []).map(normaliseSource),
    summary: raw.latest_summary ?? null,
    latest_summary: raw.latest_summary ?? null,
    // Backend returns latest_deepdive: TSX string | null
    assets: { deepdive: raw.latest_deepdive ?? null },
    jobs: [],
  };
}

function mapJobStatus(raw: string): Job["status"] {
  switch (raw) {
    case "pending":
      return "queued";
    case "processing":
      return "running";
    case "done":
      return "completed";
    case "failed":
      return "failed";
    default:
      return "queued";
  }
}

// ---------------------------------------------------------------------------
// Dashboard
// ---------------------------------------------------------------------------

export async function getDashboard(): Promise<WorkspaceCard[]> {
  const res = await fetch(`${API_BASE}/dashboard`, {
    headers: await authHeaders(),
  });
  if (!res.ok) throw new Error(`GET /dashboard failed: ${res.status}`);
  return res.json();
}

// ---------------------------------------------------------------------------
// Workspaces
// ---------------------------------------------------------------------------

export async function createWorkspace(name: string): Promise<Workspace> {
  const res = await fetch(
    `${API_BASE}/workspaces?name=${encodeURIComponent(name)}`,
    { method: "POST", headers: await authHeaders() },
  );
  if (!res.ok) throw new Error(`POST /workspaces failed: ${res.status}`);
  return normaliseWorkspace(await res.json());
}

export async function getWorkspace(id: string): Promise<Workspace | null> {
  const res = await fetch(`${API_BASE}/workspaces/${id}`, {
    headers: await authHeaders(),
  });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`GET /workspaces/${id} failed: ${res.status}`);
  return normaliseWorkspace(await res.json());
}

export async function deleteWorkspace(id: string): Promise<void> {
  const res = await fetch(`${API_BASE}/workspaces/${id}`, {
    method: "DELETE",
    headers: await authHeaders(),
  });
  if (!res.ok)
    throw new Error(`DELETE /workspaces/${id} failed: ${res.status}`);
}

// ---------------------------------------------------------------------------
// Sources
// ---------------------------------------------------------------------------

export async function getSources(workspaceId: string): Promise<Source[]> {
  const res = await fetch(`${API_BASE}/workspaces/${workspaceId}/sources`, {
    headers: await authHeaders(),
  });
  if (!res.ok)
    throw new Error(
      `GET /workspaces/${workspaceId}/sources failed: ${res.status}`,
    );
  return (await res.json()).map(normaliseSource);
}

export async function createSource(
  workspaceId: string,
  title: string,
  sourceType: Source["source_type"],
  mimeType: string,
  originalFilename: string,
): Promise<Source> {
  const res = await fetch(`${API_BASE}/workspaces/${workspaceId}/sources`, {
    method: "POST",
    headers: await authHeaders(),
    body: JSON.stringify({
      title,
      source_type: sourceType,
      mime_type: mimeType,
      original_filename: originalFilename,
    }),
  });
  if (!res.ok)
    throw new Error(
      `POST /workspaces/${workspaceId}/sources failed: ${res.status}`,
    );
  return normaliseSource(await res.json());
}

export async function getUploadUrl(
  sourceId: string,
): Promise<UploadUrlResponse> {
  const res = await fetch(`${API_BASE}/sources/${sourceId}/upload-url`, {
    method: "POST",
    headers: await authHeaders(),
  });
  if (!res.ok)
    throw new Error(
      `POST /sources/${sourceId}/upload-url failed: ${res.status}`,
    );
  return res.json();
}

export function uploadFileToBlob(
  uploadUrl: string,
  file: File,
  onProgress?: (pct: number) => void,
): Promise<void> {
  // Direct PUT to Azure Blob Storage — no Authorization header here,
  // the SAS token embedded in uploadUrl is the credential.
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("PUT", uploadUrl);
    xhr.setRequestHeader("x-ms-blob-type", "BlockBlob");
    xhr.setRequestHeader(
      "Content-Type",
      file.type || "application/octet-stream",
    );
    if (onProgress) {
      xhr.upload.onprogress = (e) => {
        if (e.lengthComputable)
          onProgress(Math.round((e.loaded / e.total) * 100));
      };
    }
    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) resolve();
      else reject(new Error(`Blob upload failed: ${xhr.status}`));
    };
    xhr.onerror = () => reject(new Error("Blob upload network error"));
    xhr.send(file);
  });
}

export async function completeUpload(
  sourceId: string,
  blobPath: string,
  mimeType: string,
  originalFilename: string,
): Promise<Partial<Source>> {
  const res = await fetch(`${API_BASE}/sources/${sourceId}/upload-complete`, {
    method: "POST",
    headers: await authHeaders(),
    body: JSON.stringify({
      blob_path: blobPath,
      mime_type: mimeType,
      original_filename: originalFilename,
    }),
  });
  if (!res.ok)
    throw new Error(
      `POST /sources/${sourceId}/upload-complete failed: ${res.status}`,
    );
  // Backend returns only {id, storage_uri, status} — caller merges onto full source
  return res.json();
}

/** Convenience: run the full 3-step upload and return the finalised source. */
export async function uploadSource(
  workspaceId: string,
  file: File,
  onProgress?: (pct: number) => void,
): Promise<Source> {
  const sourceType: Source["source_type"] = file.type.includes("pdf")
    ? "pdf"
    : file.type.includes("audio")
      ? "audio"
      : "pdf";

  const source = await createSource(
    workspaceId,
    file.name,
    sourceType,
    file.type,
    file.name,
  );
  const { upload_url, blob_path } = await getUploadUrl(source.id);
  await uploadFileToBlob(upload_url, file, onProgress);
  const completed = await completeUpload(
    source.id,
    blob_path,
    file.type || "application/octet-stream",
    file.name,
  );
  // completeUpload returns only {id, storage_uri, status} — merge back onto
  // the full source so fields like source_type/type/name are never undefined.
  return { ...source, ...completed };
}

// ---------------------------------------------------------------------------
// Sources — text and link attachment
// ---------------------------------------------------------------------------

export async function attachText(
  sourceId: string,
  textContent: string,
): Promise<Source> {
  const res = await fetch(`${API_BASE}/sources/${sourceId}/text`, {
    method: "PUT",
    headers: await authHeaders(),
    body: JSON.stringify({ text_content: textContent }),
  });
  if (!res.ok)
    throw new Error(`PUT /sources/${sourceId}/text failed: ${res.status}`);
  return normaliseSource(await res.json());
}

export async function attachLink(
  sourceId: string,
  url: string,
): Promise<Source> {
  const res = await fetch(`${API_BASE}/sources/${sourceId}/link`, {
    method: "PUT",
    headers: await authHeaders(),
    body: JSON.stringify({ url }),
  });
  if (!res.ok)
    throw new Error(`PUT /sources/${sourceId}/link failed: ${res.status}`);
  return normaliseSource(await res.json());
}

// ---------------------------------------------------------------------------
// Sources — delete + status poll
// ---------------------------------------------------------------------------

export async function deleteSource(sourceId: string): Promise<void> {
  const res = await fetch(`${API_BASE}/sources/${sourceId}`, {
    method: "DELETE",
    headers: await authHeaders(),
  });
  if (!res.ok)
    throw new Error(`DELETE /sources/${sourceId} failed: ${res.status}`);
}

export async function pollSourceStatus(
  sourceId: string,
): Promise<SourceStatusResponse> {
  const res = await fetch(`${API_BASE}/sources/${sourceId}`, {
    headers: await authHeaders(),
  });
  if (!res.ok)
    throw new Error(`GET /sources/${sourceId} failed: ${res.status}`);
  return res.json();
}

// ---------------------------------------------------------------------------
// Deep Dive — trigger + poll
// ---------------------------------------------------------------------------

/**
 * POST /workspaces/{wid}/deepdive
 *
 * Tells the backend to (re-)generate the DEEPDIVE artifact for this workspace.
 * The backend queues a background task, updates the deepdive artifact in DB,
 * and returns a job record.
 */
export async function triggerAssetGeneration(
  workspaceId: string,
  _assetType: "deepdive",
): Promise<Job> {
  const res = await fetch(`${API_BASE}/workspaces/${workspaceId}/deepdive`, {
    method: "POST",
    headers: await authHeaders(),
  });
  if (!res.ok)
    throw new Error(
      `POST /workspaces/${workspaceId}/deepdive failed: ${res.status}`,
    );
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const raw: any = await res.json();
  return {
    id: raw.id ?? raw.job_id ?? `deepdive-${workspaceId}`,
    type: "deepdive",
    status: mapJobStatus(raw.status ?? "pending"),
    updatedAt: raw.updated_at ?? raw.created_at ?? new Date().toISOString(),
  };
}

/**
 * Polls job status by re-fetching the workspace and synthesising a Job list.
 * Once `POST /workspaces/{wid}/jobs` exists on the backend this can be replaced.
 */
export async function pollJobStatus(workspaceId: string): Promise<Job[]> {
  const workspace = await getWorkspace(workspaceId);
  if (!workspace) return [];

  // Synthesise one job entry per type based on workspace state
  const jobs: Job[] = [];

  const hasProcessing = workspace.sources.some(
    (s) => s.status === "pending" || s.status === "processing",
  );
  if (hasProcessing) {
    jobs.push({
      id: `synth-ingest-${workspaceId}`,
      type: "ingest",
      status: "running",
      updatedAt: new Date().toISOString(),
    });
  }

  jobs.push({
    id: `synth-deepdive-${workspaceId}`,
    type: "deepdive",
    status: workspace.assets.deepdive ? "completed" : "queued",
    updatedAt: workspace.created_at,
  });

  return jobs;
}
