# .github/workflows/destroy.yml
name: Terraform Destroy

on:
  workflow_dispatch: # manual trigger only

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: set-variables
        shell: "pwsh"
        run: |
          @("ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}",
            "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}",
            "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}",
            "ARM_USE_OIDC=true",
            "ARM_USE_AZUREAD=true") | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        shell: "pwsh"
        run: terraform init

      - name: Destroy Terraform Resources
        shell: "pwsh"
        run: terraform destroy -auto-approve
