name: Terraform Destroy

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: "Optional: Lock ID to force unlock before destroy"
        required: false

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set-variables
        shell: "pwsh"
        run: |
          @("ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}",
            "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}",
            "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}",
            "ARM_USE_OIDC=true",
            "ARM_USE_AZUREAD=true") | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        shell: "pwsh"
        run: terraform init

      - name: Force Unlock (if needed)
        if: ${{ inputs.lock_id != '' }}
        shell: "pwsh"
        run: terraform force-unlock -force ${{ inputs.lock_id }}

      - name: Terraform Destroy
        shell: pwsh
        run: |
          terraform state list | grep azurerm_virtual_network.notewise_vnet
          terraform state show azurerm_virtual_network.notewise_vnet
          terraform destroy "-target=azurerm_virtual_network.notewise_vnet" -auto-approve

